home/urls.py
from . import views
from django.urls import path


app_name = "home"
urlpatterns = [
    path("home/",views.HomeView.as_view(),name="home"),
    path("detail/<slug:epi_slug>/",views.VideoDetailView.as_view(),name="video") , 
    
]

my_project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView , SpectacularRedocView , SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls",namespace="home")),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("order/",include("order.urls",namespace="order")),
    path("api/home/",include("home.api_urls")),
    path("api/accounts/",include("accounts.api_urls")),
    path("api/order/",include("order.api_urls")),
     # YOUR PATTERNS
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from . import views
from django.urls import path


app_name = 'order'
urlpatterns = [
    path("cart/add/<slug:course_slug>/",views.CartAddView.as_view(),name='cart_add') ,
    path("cart/remove/<slug:course_slug>/",views.CartRemoveView.as_view(),name="cart_remove"),
    path("cart/",views.CartDetailView.as_view(),name="cart"),
    path("create/",views.OrderCreateView.as_view(),name="order_create"),
    path("pay/<int:order_id>/",views.OrderPayView.as_view(),name="order_pay"),
    path("verify/",views.OrderVerifyView.as_view(),name="order_verify"),
    path("detail/<int:order_id>/",views.OrderDetailView.as_view(),name="detail"),
    path("coupon/<int:order_id>/",views.CouponApplyView.as_view(),name='coupon')
]

home/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from accounts.models import User
# Create your models here.


'''

'''




class Course(models.Model):
    user = models.ManyToManyField(User , related_name='courses')
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    paid = models.BooleanField(default=True)
    price = models.PositiveIntegerField(null=True , blank=True)
    image = models.ImageField(upload_to='images/%Y/%M/%d/',blank=True , null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    



class Episode(models.Model):
    course = models.ForeignKey(Course , on_delete=models.CASCADE , related_name="episodes")
    video = models.FileField(upload_to='episodes/%Y/%M/%d/')
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("created",)
    

    def __str__(self):
        return f"{self.title}"

    def get_absoulute_url(self):
        return reverse('home:video', args=[self.slug])
    


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL , on_delete=models.CASCADE , related_name='u_comments')
    course = models.ForeignKey(Course , on_delete=models.CASCADE , related_name="c_comments")
    reply = models.ForeignKey("self",on_delete=models.CASCADE , related_name="r_comments",null=True,blank=True)
    is_reply = models.BooleanField(default=False)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.course} - {self.text[:30]}"

home/forms.py
from django import forms 



class SearchForm(forms.Form):
    search = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"search your course here ..."}))

home/views.py
from django.shortcuts import render ,redirect, get_object_or_404
from django.views import View
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from .models import Episode , Course
from .forms import SearchForm
# Create your views here.


class HomeView(View):
    form_class = SearchForm
    def get(self,request):
        search = request.GET.get("search")
        courses = cache.get_or_set(f"courses_list_{request.user.id}",
                                   lambda:Course.objects.all(),timeout= 60 * 15 )
        if search:
            courses = courses.filter(title__icontains=search)
        return render(request,"home/home.html",{"courses":courses,"form":self.form_class})


class VideoDetailView(LoginRequiredMixin,View):    
    def get(self,request , epi_slug):
        episode = get_object_or_404(Episode , slug=epi_slug)
        if episode.course.paid is False:
            messages.error(request,"You cant watch this video", 'danger')
            return redirect("home:home")
        return render(request,"home/detail.html",{"episode":episode})

home/templates/home/detail.html
{% extends 'base.html' %}


{% block content %}
    <div class="btn-group">
        <a class="btn btn-danger" href="">{{ episode.course.title }}</a>
        <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="visually-hidden">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
        {% for ep_course in episode.course.episodes.all %}
            <li><a class="dropdown-item" href="{% url 'home:video' ep_course.slug %}">Episode {{ forloop.counter }}</a></li>
        {% endfor %}
        </ul>
    </div><br></br>


    <video src="{{ episode.video.url }}", style="height: 500px;width: 500px;"controls></video><br></br>   
    <p> Title : {{ episode.title }}</p>
    <p>{{ episode.created }}</p>
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}

{% block extra  %}
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
{% endblock %}

{% block content %}
  <h1>Course Hub </h1><br>  
  <form action="">
    {{form.as_p}}
    <input type="submit" value="Search">
  </form>
  
    {% for course in courses %}
      <!-- Example split danger button -->
      <div class="card" style="width: 18rem;">
        <img src="{{ course.image.url }}" alt="">
        <div class="card-body">
          <h5 class="card-title">{{ course.title }}</h5>
          <p class="card-text">some detials about video</p>
          {% if request.user in course.user.all and course.paid == True and request.user.is_authenticated %}
            <a href="{% url 'home:video' course.episodes.first.slug  %}" class="btn btn-primary">Watch</a>
          {% else %}
            <p>{{ course.price }} Toman</p>
            <a href="{% url 'order:cart_add' course.slug %}" class="btn btn-primary">Add to cart</a>
          {% endif %}
        </div>
      </div><br></br> 
    {% endfor %}

{% endblock %}