accounts/urls.py
from . import views
from django.urls import path


app_name = "accounts"
urlpatterns = [
    path("register/",views.UserRegisterView.as_view(),name="register"),
    path("verify_code/",views.UserVerifyRegisterCodeView.as_view(),name="verify_code"),
    path("resend_code/",views.ResendOtpCodeView.as_view(),name="resend_code"),
    path("login/",views.UserLoginView.as_view(),name="login"),
    path("logout/",views.UserLogoutView.as_view(),name="logout"),
    path("reset/",views.UserPasswordResetView.as_view(),name='password_reset') , 
    path("reset/done/",views.UserPaswwordResetDoneView.as_view(),name='password_reset_done') ,
    path("reset/confirm/<uidb64>/<token>/",views.UserPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path("reset/complete/",views.UserPasswordResetCompleteView.as_view(),name="password_reset_complete")
]

home/urls.py
from . import views
from django.urls import path


app_name = "home"
urlpatterns = [
    path("home/",views.HomeView.as_view(),name="home"),
    path("detail/<slug:epi_slug>/",views.VideoDetailView.as_view(),name="video") , 
    
]

my_project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView , SpectacularRedocView , SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls",namespace="home")),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("order/",include("order.urls",namespace="order")),
    path("api/home/",include("home.api_urls")),
    path("api/accounts/",include("accounts.api_urls")),
    path("api/order/",include("order.api_urls")),
     # YOUR PATTERNS
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from .managers import UserManager
from django.contrib.auth.models import PermissionsMixin
from datetime import datetime , timedelta
from django.utils import timezone
# Create your models here.



class User(AbstractBaseUser , PermissionsMixin):
    username = models.CharField(max_length=100,  unique=True)
    email = models.EmailField(max_length=100 , unique=True )
    date_joined  = models.DateTimeField(auto_now_add=True)
    is_staff =  models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ["email"]

    objects = UserManager()
    
    def __str__(self):
        return f"{self.username} - {self.email}"


class OtpCode(models.Model):
    code = models.SmallIntegerField()
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    
    def is_expired(self):
        return self.created < timezone.now() - timedelta(minutes=3)

    def __str__(self):
        return f"{self.email} - {self.code}"

accounts/forms.py
from django import forms
from accounts.models import User
from django.contrib.auth.forms import ReadOnlyPasswordHashField 
from django.core.exceptions import ValidationError


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label="password",widget=forms.PasswordInput)
    password2 = forms.CharField(label="confirm password",widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username","email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd["password1"] and cd['password2'] and cd["password1"] != cd['password2']:
            raise ValidationError("Passwords must match !!!")
        return cd['password2']

    def save(self , commit=True):
        user =  super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(help_text="you can change password from <a href=\'../password/\'>this link <a/>")
    class Meta:
        model = User
        fields = ("username","email","password", "is_active", "is_staff")
        


class UserRegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class":"form-control"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control"}))
    password2 = forms.CharField(label="confirm password",widget=forms.PasswordInput(attrs={"class":"form-control"}))
    
    def clean_username(self):
        username = self.cleaned_data["username"]
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError("This user with this username already regsitered ! ")
        return username
        
    def clean_email(self):
        email = self.cleaned_data["email"]
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError("This user with this email already regsitered ! ")
        return email
    
    def clean(self):
        cd =  super().clean()
        p1 = cd.get("password")
        p2 = cd.get("password2")
        if p1 and p2 and p1 != p2 :
            raise ValidationError("Passwords must match ! ")
        return cd

class UserReigisterVerifyCodeForm(forms.Form):
    code = forms.IntegerField()




class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder":"enter username","class":"form-control"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"enter password","class":"form-control"}))

accounts/views.py
from django.shortcuts import render , redirect
from django.views import View
from django.contrib.auth import authenticate , login , logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from datetime import datetime
from .models import User , OtpCode
from .forms import UserRegistrationForm , UserLoginForm , UserReigisterVerifyCodeForm
from .tasks import send_otp
from utils import Data
import pytz
import random

# Create your views here.


class UserRegisterView(View):
    """
    Sends an otp code to the user (through email) as soon as it delivers valid data
    """
    form_class = UserRegistrationForm
    template_name = "accounts/register.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)


    def get(self,request):
        form = self.form_class()
        return render(request,self.template_name,{"form":form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            random_code = random.randint(1000,9999)
            OtpCode.objects.create(code=random_code,email=cd['email'])
            send_otp.apply_async(args=[cd['email'], random_code])
            data = Data(request,cd["username"],str(datetime.now(tz=pytz.timezone("Asia/Tehran"))))
            data.save_data(cd["email"],cd['password'])
            return redirect("accounts:verify_code")
        return render(request,self.template_name,{"form":form})

class UserVerifyRegisterCodeView(View):
    """
    Creates an user in the database when user verifys correct otp code and
    completes user registraion proccess
    """
    form_class = UserReigisterVerifyCodeForm
    template_name = "accounts/verify_code.html"

    def get(self,request):
        form = self.form_class()    
        return render(request,self.template_name,context={"form":form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        session = request.session["user_data"]
        username_session = list(session.keys())[0]
        code_instance = OtpCode.objects.get(email=session[username_session]["email"])
        if form.is_valid():
            if code_instance.is_expired():
                messages.error(request,"this code has been expired","danger")
                return redirect("accounts:verify_code")
            if code_instance.code == form.cleaned_data["code"]:
                User.objects.create_user(
                    username=username_session,
                    email=session[username_session]["email"],
                    password=session[username_session]['password'])
                messages.success(request,"User has been created successfully","success")
                code_instance.delete()
                return redirect("home:home")
            else:
                messages.error(request,"code is wrong please try again !","danger")
                return redirect("accounts:verify_code")
        return render(request,self.template_name,context={"form":form})

class UserLoginView(View):
    form_class = UserLoginForm
    template_name = "accounts/login.html"

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get("next")
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect("home:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self,request):
        form = self.form_class()
        return render(request,self.template_name ,{'form':form})
    
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = authenticate(request,username=form.cleaned_data["username"],password=form.cleaned_data["password"])
            if user is not None:
                login(request,user) 
                messages.success(request,"User has been logged in successfully",'success')
                data = Data(request,form.cleaned_data["username"],str(datetime.now(tz=pytz.timezone("Asia/Tehran"))))
                data.save_last_login(request)
                if self.next:
                    return redirect(self.next)
                return redirect("home:home")
            else:
                messages.error(request,"Username or password is wrong","danger")
                return redirect("accounts:login")
        return render(request,self.template_name ,{'form':form})
    




class UserLogoutView(LoginRequiredMixin,View):
    def get(self,request):
        logout(request)
        messages.success(request,"User logged out successfully","success")
        return redirect("home:home")    




class ResendOtpCodeView(View):
    def get(self,request):
        session = request.session.get("user_data")
        if not session:
            messages.error(request, "Session expired, please try again.", "danger")
            return redirect("accounts:register") 
        username_session = list(session.keys())[0]
        old_code = OtpCode.objects.filter(email=session[username_session]['email']).first()
        if old_code:
            if  old_code.is_expired():
                old_code.delete()
                random_code = random.randint(1000,9999)
                new_code = OtpCode.objects.create(code=random_code , email=session[username_session]['email'])
                send_otp.apply_async(args=[session[username_session]['email'], random_code])
                messages.success(request,"New code has been resend to your email","success")
            else:
                messages.error(request,"You cant resend code now","danger")
        else:
            messages.error(request,"No otp code found for this email","danger")
        return redirect("accounts:verify_code")
    


class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'


class UserPaswwordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'

class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy("accounts:password_reset_complete")

class UserPasswordResetCompleteView(auth_views.PasswordResetCompleteView):
    template_name = "accounts/password_reset_complete.html"

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block extra %}
    <link rel="stylesheet" href="{% static 'accounts/css/style_login.css' %}">
{% endblock %}


{% block content %}
<div class="form-wrapper">
  <div class="form-container">
    <form action="" method="post">
      <h2 class="form-title">Login</h2>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Login" class="btn btn-primary w-100">
      <div class="text-center mt-3">
        <a href="{% url 'accounts:password_reset' %}" class="btn btn-link">Forgot password?</a>
      </div>
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}


{% block content %}
    <p>Password has been changed successfully</p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    {% if validlink %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}

            {% if form.errors %}
                <ul class="errors">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li><strong>{{ field.label }}:</strong> {{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <input type="submit" value="Change">
        </form>
    {% else %}
        <p class="alert alert-danger">Link is unvalid at this time , Please try again</p>
    {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}


{% block content %}
    <p>We sent you an email</p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Send">
    </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block extra %}
    <link rel="stylesheet" href="{% static 'accounts/css/style_register.css' %}">
{% endblock %}

{% block content %}
<div class="form-wrapper">
  <div class="form-container">
    <form action="" method="post">
      <h2 class="form-title">Register</h2>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Register" class="btn btn-primary w-100">
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/verify_code.html
{% extends 'base.html' %}

{% block content %}
    <h3>Verify Code</h3>
    <form action="{% url 'accounts:verify_code' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Verify" class="btn btn-info">
    </form>
{% endblock %} 