accounts/urls.py
from . import views
from django.urls import path


app_name = "accounts"
urlpatterns = [
    path("register/",views.UserRegisterView.as_view(),name="register"),
    path("verify_code/",views.UserVerifyRegisterCodeView.as_view(),name="verify_code"),
    path("resend_code/",views.ResendOtpCodeView.as_view(),name="resend_code"),
    path("login/",views.UserLoginView.as_view(),name="login"),
    path("logout/",views.UserLogoutView.as_view(),name="logout"),
    path("reset/",views.UserPasswordResetView.as_view(),name='password_reset') , 
    path("reset/done/",views.UserPaswwordResetDoneView.as_view(),name='password_reset_done') ,
    path("reset/confirm/<uidb64>/<token>/",views.UserPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path("reset/complete/",views.UserPasswordResetCompleteView.as_view(),name="password_reset_complete")
]

home/urls.py
from . import views
from django.urls import path


app_name = "home"
urlpatterns = [
    path("home/",views.HomeView.as_view(),name="home"),
    path("detail/<slug:epi_slug>/",views.VideoDetailView.as_view(),name="video") , 
    
]

my_project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView , SpectacularRedocView , SpectacularSwaggerView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("home.urls",namespace="home")),
    path("accounts/",include("accounts.urls",namespace="accounts")),
    path("order/",include("order.urls",namespace="order")),
    path("api/home/",include("home.api_urls")),
    path("api/accounts/",include("accounts.api_urls")),
    path("api/order/",include("order.api_urls")),
     # YOUR PATTERNS
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from . import views
from django.urls import path


app_name = 'order'
urlpatterns = [
    path("cart/add/<slug:course_slug>/",views.CartAddView.as_view(),name='cart_add') ,
    path("cart/remove/<slug:course_slug>/",views.CartRemoveView.as_view(),name="cart_remove"),
    path("cart/",views.CartDetailView.as_view(),name="cart"),
    path("create/",views.OrderCreateView.as_view(),name="order_create"),
    path("pay/<int:order_id>/",views.OrderPayView.as_view(),name="order_pay"),
    path("verify/",views.OrderVerifyView.as_view(),name="order_verify"),
    path("detail/<int:order_id>/",views.OrderDetailView.as_view(),name="detail"),
    path("coupon/<int:order_id>/",views.CouponApplyView.as_view(),name='coupon')
]

templates/inc/messages.html
{% if messages  %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{ msg }}</p>
    {% endfor %}
{% endif %} 

templates/inc/navabr.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div>
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:home' %}">Home</a>
      {% if  not request.user.is_authenticated %}
      <a class="navbar-brand" href="{% url 'accounts:register' %}">Register</a>
      <a class="navbar-brand" href="{% url 'accounts:login' %}">Login</a>
      {% else %}
      <a class="navbar-brand" href="{% url 'order:cart' %}"> Cart {{ cart|length }}</a>
      <a class="navbar-brand" href="{% url 'accounts:logout' %}">Logout</a>
      {% endif %}
    </div>
  </div>
  </nav>